name: Hasta llegar el tempo del tu vida

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs: 
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Fuck Microsoft
        shell: zsh
        run: |
          echo "Microsoft has been the single worst company around the world"
          echo "So Microsoft, Fuck you!"
